FROM debian:jessie
MAINTAINER kontakt@trzeci.eu

RUN rm /bin/sh && ln -s /bin/bash /bin/sh && \
	apt-get -y update && apt-get install -y --no-install-recommends \
	cmake git-core ca-certificates build-essential python nodejs && \
	\
	git clone --depth 1 https://github.com/juj/emsdk.git emsdk_portable && \
	cd emsdk_portable && \
	rm -fr .git && \
	rm -fr bin && \
	./emsdk update && \
	./emsdk install --build=MinSizeRel {EMSCRIPTEN_SDK_TAG} && \
	./emsdk activate {EMSCRIPTEN_SDK_TAG} && \
	\
	sed -i -e 's/NODE_JS=.*/NODE_JS="nodejs"/g' ~/.emscripten && \
	find . -name "CMakeFiles" -type d -prune -exec rm -fr {} \; && \
	find . -name "*.o" -exec rm {} \; && \
	find . -name "*.a" -exec rm {} \; && \
	emscripten_version=$(find clang/*/src/emscripten-version.txt) && \
	mv $emscripten_version emscripten-version.txt && \
	rm -rf clang/*/src && \ 
	mkdir -p $(echo "$(dirname "$emscripten_version")") && \ 
	mv emscripten-version.txt $emscripten_version && \
	rm -rf emscripten/*/.git && \
	rm -rf zips && \
	rm -rf node && \
	rm -rf emscripten/*/tests && \
	\
	for prog in em++ em-config emar emcc emconfigure emmake emranlib emrun emscons emcmake; do \
	ln -sf /emsdk_portable/emscripten/{EMSCRIPTEN_SDK_DIR}/$prog /usr/local/bin; done && \
	\
	EMSCRIPTEN=/emsdk_portable/emscripten/{EMSCRIPTEN_SDK_DIR} && \
	\
	emcc --version && \
	mkdir -p /tmp/emscripten_test && pushd /tmp/emscripten_test && \
	echo "#include <iostream>" > test.cpp && echo 'int main() { std::cout<< "HELLO" << std::endl; return 0;}' >> test.cpp && \
	em++ -O2 test.cpp -o test.js && \
	em++ test.cpp -o test.js && \
	nodejs test.js && \
	popd && \
	rm -fr /tmp/emscripten_test && \
	\
	apt-get -y --purge remove build-essential gcc perl git-core ca-certificates && \
	apt-get -y autoremove && \
	apt-get clean

# SETUP SDK
ENV EMSCRIPTEN=/emsdk_portable/emscripten/{EMSCRIPTEN_SDK_DIR}

VOLUME ["/src"]
WORKDIR /src
